### PR TITLE
Remove trailing space

### PR DESCRIPTION
**Pull request by Rexios80**

### CODE REVIEW

**Comment by gmpassos** [comment]
Thank you for the PR.

Could you please add a unit test? Also, you need to adjust the current failing tests.

Best regards.

**Comment by Rexios80** [comment]
I updated the existing tests which should sufficiently cover this change

**Comment by Rexios80** [comment]
@gmpassos Do you need anything else from me on this? That CI failure does not appear to be the fault of this PR.

**Comment by Rexios80** [comment]
Thank you for merging this! When do you plan on releasing it to pub.dev?

**Comment by gmpassos** [comment]
Published (v2.0.1) 👍

**Pull request merged**
